version: "2.1"
services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /mnt/nas/appdata/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /mnt/nas/appdata/radarr:/config
#      - /path/to/movies:/movies #optional
#      - /path/to/downloadclient-downloads:/downloads #optional
      - /mnt/nas:/mnt/nas
    ports:
      - 7878:7878
    restart: unless-stopped
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /mnt/nas/appdata/sonarr:/config
#      - /path/to/tvseries:/tv #optional
#      - /path/to/downloadclient-downloads:/downloads #optional
      - /mnt/nas:/mnt/nas
    ports:
      - 8989:8989
    restart: unless-stopped