version: "3"
services:
  homeassistant:
    container_name: home-assistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - /mnt/nas/appdata/home-assistant:/config
    environment:
      - TZ=Europe/London
    restart: unless-stopped
    privileged: true
    network_mode: host