version: "3"
services:
  homeassistant:
    container_name: home-assistant
    image: "lscr.io/linuxserver/homeassistant:latest"
    volumes:
      - home-assistant_config:/config
      - /run/dbus:/run/dbus:ro
    environment:
      - TZ=Europe/London
      - PUID=1000
      - PGID=1000
    restart: unless-stopped
    privileged: true
    network_mode: host
