version: "3"
services:
  mqtt:
    container_name: mqtt
    image: "eclipse-mosquitto"
    volumes:
      - mqtt_config:/mosquitto/config
      - mqtt_data:/mosquitto/data
      - mqtt_log:/mosquitto/log
    environment:
      - TZ=Europe/London
    restart: unless-stopped
volumes:
  mqtt_config:
  mqtt_data:
  mqtt_log:
ports:
  - 58880:1883
  - 58881:9001